### PR TITLE
add: print rotation, show previous and next prints on the same image.

### PR DESCRIPTION
**Pull request by AzureRodrigo**
Added new optional parameters to `config.json`:

- `image: rotation` receives a number, which is used to rotate the image.
- `image: previous` object with the same parameters as `image`, used to display the previous image in the current template.
- `image: next` object with the same parameters as `image`, used to display the next image in the current template.

### CODE REVIEW

**Comment by dral3x** [comment]
Hey @AzureRodrigo, thanks for this nice addiction!

Before merging and release this new feature, can you please fix the broken tests and add new ones to ensure how the feature works?

**Comment by dral3x** [comment]
I just merged another PR that enabled testing on CI, to ease the work for everybody 👍 
Simply rebase your branch from my master and update the PR.
Thanks!

**Comment by AzureRodrigo** [comment]
Added: test for rotate and previous new functions in:

-spec/screen3
-spec/template3-full
-spec/framer_action_spec.rb

**Review by dral3x — APPROVED** [review]
LGTM 👍  Well done @AzureRodrigo, and thank you!

I'm going to merge it and release a new version soon.

**Comment by CostaPedroHenrique** [comment]
Quando sai a nova versão?

**Pull request merged**
